package.path = "test/?.lua;test/mock/?.lua;" .. package.path
local envMock = require("env")
local gamechat = require("gamechat")
local passed, failed = 0, 0
local function check(label, condition) assert(condition, label); passed = passed + 1 end
local function scenario(name, fn)
	local ok, err = pcall(fn)
	if ok then print("ok " .. name) else failed = failed + 1; print("FAIL " .. name .. ": " .. tostring(err)) end
end
local function boot()
	local h = envMock.new()
	local chat = gamechat(h)
	local app = assert(h.boot()); h.settle(1)
	app.config.set("permissions.mode", "full")
	return h, app, chat, app.env.require("runtime/chatloops")
end
local function start(app, name, args)
	return app.tools.dispatch({ name = name, arguments = app.env.require("runtime/util").encode(args) }, app.sessions.current().toolContext())
end

scenario("auto-chat cycles, completes, and surfaces real progress", function()
	local h, app, chat, loops = boot()
	local result = start(app, "auto_chat", { messages = { "One", "Two" }, interval = 5, count = 3 })
	check("start succeeds through dispatch", result.ok and result.data.id)
	check("indicator becomes visible", h.byName("ChatLoops").Visible)
	h.settle(16)
	check("exactly three messages sent", #chat.sent == 3)
	check("messages cycle in order", chat.sent[1].text == "One" and chat.sent[2].text == "Two" and chat.sent[3].text == "One")
	check("real intervals are respected", chat.sent[2].at - chat.sent[1].at >= 5000)
	check("completion recorded", loops.list()[1].state == "completed" and loops.list()[1].completed == 3)
	check("indicator goes away at completion", not h.byName("ChatLoops").Visible)
	check("status works after completion", start(app, "chat_loop_status", { id = result.data.id }).text:find("completed", 1, true))
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("quiz accepts the first answer and ignores self, duplicates, and other channels", function()
	local h, app, chat, loops = boot()
	check("quiz starts", start(app, "quiz_bot", { interval = 10, count = 2, questions = {
		{ question = "Two plus two?", answer = "four", aliases = { "4" } },
		{ question = "Sky colour?", answer = "blue" },
	} }).ok)
	h.settle(1)
	chat.receive("4", 1, "TestPlayer")
	chat.receive("4", 2, "Other channel", "RBXTeam")
	check("self and other channel do not win", not loops.list()[1].winner)
	chat.receive("4!", 2, "Alice", nil, "answer-1")
	chat.receive("4!", 2, "Alice", nil, "answer-1")
	chat.receive("four", 3, "Bob")
	h.settle(5)
	check("first correct answer wins", loops.list()[1].scores["2"].points == 1 and not loops.list()[1].scores["3"])
	check("winner is announced", chat.sent[2].text == "Alice got it right!")
	h.settle(21)
	check("second question is asked", chat.sent[3].text:find("Sky colour?", 1, true))
	check("timeout reveals the answer", chat.sent[4].text == "Time's up! Answer: blue")
	check("quiz completes after two rounds", loops.list()[1].state == "completed")
	check("score is inspectable", start(app, "chat_loop_status", {}).text:find("Alice: 1 points", 1, true))
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("auto-reply is bounded and does not respond to itself or the system", function()
	local h, app, chat, loops = boot()
	check("reply starts", start(app, "auto_reply", { interval = 5, count = 2, rules = { { trigger = "hello", response = "Welcome!", exact = true } } }).ok)
	chat.receive("hello", 1, "TestPlayer")
	chat.receive("hello", nil, "System")
	chat.receive("hello there", 2, "Alice")
	h.settle(1)
	check("ignored input sends nothing", #chat.sent == 0)
	chat.receive("hello!", 2, "Alice", nil, "one")
	chat.receive("hello!", 2, "Alice", nil, "one")
	h.settle(1)
	check("one matching input produces one reply", #chat.sent == 1)
	chat.receive("hello", 3, "Bob")
	h.settle(5)
	check("messages during cooldown are not queued", #chat.sent == 1)
	chat.receive("hello", 3, "Bob")
	h.settle(1)
	check("second reply completes the loop", #chat.sent == 2 and loops.list()[1].state == "completed")
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("stop controls, session abort, clear, and removal cancel future sends", function()
	local h, app, chat, loops = boot()
	local args = { messages = { "Tick" }, interval = 5, count = 20 }
	check("first loop starts", start(app, "auto_chat", args).ok)
	h.settle(1)
	h.click(h.byName("StopChatLoops"))
	local before = #chat.sent; h.settle(7)
	check("UI stop cancels future messages", #chat.sent == before and #loops.running() == 0)
	check("second loop starts", start(app, "auto_chat", args).ok)
	check("idle session abort stops loops", app.sessions.current().abort())
	h.settle(7); check("abort prevented sending", #chat.sent == before)
	check("third loop starts", start(app, "auto_chat", args).ok)
	app.sessions.current().clear(); h.settle(7)
	check("clear stops loops", #chat.sent == before)
	check("fourth loop starts", start(app, "auto_chat", args).ok)
	app.sessions.remove(app.sessions.current().id); h.settle(7)
	check("removal stops loops", #chat.sent == before and #loops.running() == 0)
end)

scenario("transport errors, invalid input, and disabled chat never report fake success", function()
	local h, app, chat, loops = boot()
	check("unknown channel fails", not start(app, "auto_chat", { messages = { "Hello" }, channel = "Missing" }).ok)
	check("blank messages fail", not start(app, "auto_chat", { messages = { " " } }).ok)
	check("oversized messages fail", not start(app, "auto_chat", { messages = { string.rep("x", 201) } }).ok)
	check("invalid interval fails", not start(app, "auto_chat", { messages = { "Hello" }, interval = 0 }).ok)
	check("punctuation trigger fails", not start(app, "auto_reply", { rules = { { trigger = "!!!", response = "Oops" } } }).ok)
	chat.addChannel("RBXGeneral", function() error("send failed") end)
	check("start still returns before sending", start(app, "auto_chat", { messages = { "Hello" } }).ok)
	h.settle(1)
	check("failed transport stops job", loops.list()[1].state == "failed" and loops.list()[1].sent == 0)
	check("chat_send reports transport failure", not start(app, "chat_send", { message = "Hello" }).ok)
	chat.addChannel("RBXGeneral", function() return { Status = h.sandbox.Enum.TextChatMessageStatus.Floodchecked } end)
	check("chat_send reports server rejection", not start(app, "chat_send", { message = "Hello" }).ok)
	chat.addChannel("RBXGeneral")
	check("next loop starts", start(app, "auto_chat", { messages = { "Hello" } }).ok)
	app.tools.setGroupEnabled("chat", false); h.settle(6)
	check("disabling group stops its loop", #loops.running() == 0 and #chat.sent == 0)
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("loop requests honor permission denials and stop remains available", function()
	local h, app, chat, loops = boot()
	local permissions = app.env.require("agent/permissions")
	permissions.setRule("auto_chat", "deny")
	check("denied start is rejected", not start(app, "auto_chat", { messages = { "Hello" } }).ok)
	check("denied start leaves no job", #loops.list() == 0)
	permissions.setRule("auto_chat", "allow")
	check("allowed start succeeds", start(app, "auto_chat", { messages = { "Hello" } }).ok)
	permissions.setMode("readonly")
	check("stop is callable in read-only mode", start(app, "chat_loop_stop", { id = "all" }).ok)
	h.settle(6)
	check("nothing is sent after stop", #chat.sent == 0)
end)

scenario("unload disconnects listeners and stops every loop", function()
	local h, app, chat, loops = boot()
	check("start succeeds", start(app, "auto_chat", { messages = { "Hello" } }).ok)
	h.settle(1)
	local before = #chat.sent
	local history = app.env.require("runtime/gamechat").history
	local historyCount = #history
	app.destroy(); h.settle(20)
	chat.receive("after unload", 2, "Alice")
	check("no sends after unload", #chat.sent == before)
	check("no listener after unload", #history == historyCount)
	check("all loops stopped", #loops.running() == 0)
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("legacy chat uses its requested channel and filtered messages", function()
	local h = envMock.new()
	local incoming = h.Instance.new("TextBox").FocusLost
	local sent = {}
	local request = { FireServer = function(_, text, channel) sent[#sent + 1] = { text = text, channel = channel } end }
	h.services.TextChatService = { ChatVersion = h.sandbox.Enum.ChatVersion.LegacyChatService }
	h.services.ReplicatedStorage = { FindFirstChild = function(_, name)
		if name == "DefaultChatSystemChatEvents" then return { FindFirstChild = function(_, child)
			if child == "SayMessageRequest" then return request end
			if child == "OnMessageDoneFiltering" then return { OnClientEvent = incoming } end
		end } end
	end }
	local app = assert(h.boot()); h.settle(1)
	app.config.set("permissions.mode", "full")
	check("legacy auto-reply starts", start(app, "auto_reply", { channel = "Team", rules = { { trigger = "hello", response = "Hi team" } }, count = 1 }).ok)
	incoming:Fire({ Message = "hello", FromSpeaker = "Alice", SpeakerUserId = 2, OriginalChannel = "Team" })
	h.settle(1)
	check("legacy route preserves team channel", #sent == 1 and sent[1].channel == "Team" and sent[1].text == "Hi team")
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("a cancelled yielding send cannot schedule another message", function()
	local h, app, chat, loops = boot()
	chat.addChannel("RBXGeneral", function(text)
		h.sandbox.task.wait(10)
		chat.sent[#chat.sent + 1] = { text = text }
	end)
	check("loop starts", start(app, "auto_chat", { messages = { "Pending" }, interval = 5 }).ok)
	h.settle(1)
	loops.stop()
	h.settle(25)
	check("only the already submitted send completes", #chat.sent == 1)
	check("job stays stopped after send returns", loops.list()[1].state == "stopped" and loops.list()[1].completed == 0)
	check("no asynchronous errors", #h.errors() == 0)
end)

scenario("quiz and reply jobs respect duration and channel exclusivity", function()
	local h, app, chat, loops = boot()
	check("reply starts", start(app, "auto_reply", { duration = 10, rules = { { trigger = "hello", response = "Hi" } } }).ok)
	check("second loop cannot compete for the same channel", not start(app, "auto_chat", { messages = { "Hi" } }).ok)
	h.settle(11)
	check("idle job ends at its deadline", loops.list()[1].state == "completed" and #chat.sent == 0)
	check("a subagent cannot leave a chat loop running", not loops.start("auto", { messages = { "Hi" } }, { session = app.sessions.current(), depth = 1 }))
end)

scenario("independent channels share the sender without starvation", function()
	local h, app, chat, loops = boot()
	check("general loop starts", start(app, "auto_chat", { messages = { "General" }, interval = 5, count = 3 }).ok)
	check("team loop starts", start(app, "auto_chat", { messages = { "Team" }, channel = "Team", interval = 5, count = 3 }).ok)
	h.settle(27)
	check("both jobs complete", #chat.sent == 6 and #loops.running() == 0)
	check("sender alternates channels fairly", chat.sent[1].channel == "RBXGeneral" and chat.sent[2].channel == "RBXTeam"
		and chat.sent[3].channel == "RBXGeneral" and chat.sent[4].channel == "RBXTeam")
	for index = 2, #chat.sent do check("global pacing is respected", chat.sent[index].at - chat.sent[index - 1].at >= 5000) end
end)

print(string.format("chat loops: %d checks passed, %d scenarios failed", passed, failed))
os.exit(failed > 0 and 1 or 0)
