package.path = "test/?.lua;test/mock/?.lua;" .. package.path
io.stdout:setvbuf("no")
local F = require("workspace_fixture")
local suite = F.suite("Code workspace")
local case, check = suite.case, suite.check
local function has(text, needle) return tostring(text):find(needle, 1, true) ~= nil end

case("live documents, stable views and source revision guards", function()
	local f = F.new(); local store = f.env.require("runtime/code_store")
	store.init(); local doc = store.active(); local id = doc.id
	assert(store.update(id, "local x = 1\nreturn x", { origin = "typing" }))
	check("unsaved live draft is immediately visible", store.resolve(id).source == "local x = 1\nreturn x" and doc.revision == 1)
	check("unguarded existing tool write refused", not store.update(id, "return 2", { origin = "tool" }))
	check("stale write refused", not store.update(id, "return 2", { expected_revision = 0, origin = "tool" }))
	assert(store.rename(id, "draft.lua")); assert(store.close(id))
	check("closing view keeps library document", store.resolve(id).source == "local x = 1\nreturn x" and #store.openIds() == 0)
	assert(store.select(id)); check("rename/reopen retains ID", store.activeId() == id)
	local second = assert(store.create("draft.lua", "return 3"))
	check("duplicate names need exact IDs", not store.resolve("draft.lua") and store.resolve(second.id) == second)
	f.healthy(); f.close()
end)

case("verified persistence, backup recovery and corrupt/future protection", function()
	local f = F.new(); local env, h = f.env, f.h
	local store, fs = env.require("runtime/code_store"), env.require("runtime/fsx")
	store.init(); local doc = store.active(); assert(store.update(doc.id, "return 'saved'", { origin = "typing" })); assert(store.saveNow())
	local raw = assert(fs.read("code/workspace.json")); check("two verified copies", fs.read("code/workspace.backup.json") == raw)
	local originalWrite = fs.write
	fs.write = function(path, content, options) if path:find("workspace", 1, true) then originalWrite(path, content:sub(1, 10), options); return true end; return originalWrite(path, content, options) end
	assert(store.update(doc.id, "return 'new draft'", { origin = "typing" }))
	check("truncated successful write is detected", not store.saveNow() and store.storage.state == "failed")
	check("draft stays exact", doc.source == "return 'new draft'")
	fs.write = originalWrite
	local other = F.new(); for path, content in pairs(h.files) do other.h.files[path] = content end
	local recovered = other.env.require("runtime/code_store"); recovered.init()
	check("valid backup wins over corrupt primary", recovered.active().source == "return 'saved'")
	assert(recovered.saveNow()); local preserved = false
	for path, content in pairs(other.h.files) do if path:find("recovery_", 1, true) and content == raw:sub(1, 10) then preserved = true end end
	check("corrupt original preserved", preserved)
	local future = F.new(); local futureFs = future.env.require("runtime/fsx")
	assert(futureFs.write("code/workspace.json", '{"version":999}'))
	local protected = future.env.require("runtime/code_store"); protected.init()
	check("future version protected", protected.storage.state == "protected" and not protected.saveNow())
	check("future data unchanged", futureFs.read("code/workspace.json") == '{"version":999}')
	f.close(); other.close(); future.close()
end)

case("legacy migration, reserved namespace, no filesystem and source budget", function()
	local f = F.new(); local fs = f.env.require("runtime/fsx")
	local legacy = f.h.json.encode({ tabs = { { name = "Old.lua", code = "return 42" } }, active = 1 })
	assert(fs.write("code/tabs.json", legacy))
	local store = f.env.require("runtime/code_store"); store.init()
	check("legacy source migrated", store.active().source == "return 42")
	assert(store.saveNow()); check("legacy file preserved", fs.read("code/tabs.json") == legacy)
	check("oversized edit preserves current source", not store.update(store.activeId(), string.rep("a", 256001)) and store.active().source == "return 42")
	local plain = F.new({ executor = false }); local memory = plain.env.require("runtime/code_store"); memory.init()
	assert(memory.update(memory.activeId(), "return false"))
	check("plain host retains useful session source", memory.storage.state == "session_only" and not memory.preflightReplacement())
	f.close(); plain.close()
end)

case("source versions, undo/redo and coherent proposal application", function()
	local f = F.new(); local store = f.env.require("runtime/code_store"); store.init(); local doc = store.active()
	assert(store.update(doc.id, "return 1")); local version = assert(store.saveVersion(doc.id, "One"))
	assert(store.update(doc.id, "return 2")); assert(store.undoSource(doc.id)); check("source undo", doc.source == "return 1")
	assert(store.redoSource(doc.id)); check("source redo", doc.source == "return 2")
	check("stale restore refused", not store.restoreVersion(doc.id, version.id, 0))
	assert(store.restoreVersion(doc.id, version.id, doc.revision))
	local proposal = assert(store.propose(doc.id, doc.revision, "return 9"))
	local events = 0; local off = store.changed:connect(function() events = events + 1; check("applied proposal absent at notification", #store.proposals(doc.id) == 0) end)
	assert(store.applyProposal(proposal.id)); off()
	check("one coherent apply event", events == 1 and doc.source == "return 9")
	check("repeat apply cannot change revision", not store.applyProposal(proposal.id))
	local stale = assert(store.propose(doc.id, doc.revision, "return 8")); assert(store.update(doc.id, "return 7"))
	check("stale proposal preserved for review", not store.applyProposal(stale.id) and #store.proposals(doc.id) == 1 and doc.source == "return 7")
	f.healthy(); f.close()
end)

case("lexer keeps raw bytes and diff preserves exact endings", function()
	local f = F.new(); local lexer = f.env.require("runtime/code_lexer"); local diff = f.env.require("runtime/code_diff")
	local source = "--[=[comment\nend ]=]\nlocal s = [==[<tag>&\n]==] and 0xff\r\n"
	local cache = lexer.scan(source); local lines = lexer.lines(source)
	check("raw lines round trip", table.concat(lines, "\n") == source)
	check("multiline comment state", cache.states[1] ~= "" and cache.states[2] == "")
	local colored = lexer.rich(cache.lines[3], cache.spans[3], { keyword = "#fff", string = "#abc" })
	check("rich text is escaped", has(colored, "&lt;tag&gt;&amp;") and has(colored, '<font color='))
	local edit = diff.compare("a\nb\n", "a\nc\n")
	check("diff records exact sources and changed rows", edit.before == "a\nb\n" and edit.after == "a\nc\n" and edit.added == 1 and edit.removed == 1)
	local huge = diff.compare(string.rep("a\n", 500), string.rep("b\n", 500))
	check("large comparison uses bounded replacement", huge.replacement == true and huge.after == string.rep("b\n", 500))
	f.close()
end)

case("typed actions keep immutable source and pass data without interpolation", function()
	local f = F.new(); local store, inputs, runner = f.env.require("runtime/code_store"), f.env.require("runtime/code_actions"), f.env.require("tools/code_runner")
	store.init(); local doc = store.active()
	assert(store.update(doc.id, "local input = ...; print(input.text, input.flag, input.number); return input.text"))
	local action = assert(store.saveAction(doc.id, "Typed", { { key = "text", type = "string", required = true }, { key = "flag", type = "boolean", default = false }, { key = "number", type = "number", min = 0, max = 5 }, { key = "optional", type = "boolean" } }))
	local old = action.source; assert(store.update(doc.id, "error('new source')"))
	check("action snapshot remains fixed", action.source == old)
	check("action update requires observed source revision", not store.saveAction(doc.id, "Typed", action.inputs, { id = action.id, expected_revision = action.revision }))
	local text = "'); error('injected'); --"
	local params = assert(inputs.parameters(action.inputs, { text = text, number = 0 }))
	check("optional/default/zero survive", params.flag == false and params.number == 0 and params.optional == nil)
	check("invalid and unknown inputs rejected", not inputs.parameters(action.inputs, { text = text, number = 10 }) and not inputs.parameters(action.inputs, { text = text, injected = 1 }))
	local snapshot = assert(runner.actionSnapshot(action.id, action.revision, { text = text, number = 0 }))
	local result = f.run(function() return runner.run(snapshot) end)
	check("input executed as data only", result.ok and has(result.text, text) and not has(result.text, "Runtime error"))
	f.healthy(); f.close()
end)

case("runner attribution, live output, reservation and Stop", function()
	local f = F.new(); local store, runner = f.env.require("runtime/code_store"), f.env.require("tools/code_runner")
	store.init(); local doc = store.active(); assert(store.update(doc.id, "print('before'); task.wait(1); return false, nil, 7, nil"))
	local revision = doc.revision; local id = assert(runner.start(doc.id))
	check("duplicate activation rejected", not runner.start(doc.id))
	assert(store.update(doc.id, "return 'changed'")); f.h.sched.advance(1.2)
	local run = runner.runs[#runner.runs]
	check("run keeps dispatched source revision", run.id == id and run.revision == revision and run.source:find("before", 1, true))
	check("live and final output retained", #run.output > 0 and has(run.result.text, "false\tnil\t7\tnil"))
	assert(store.update(doc.id, "while true do task.wait(0.1) end")); assert(runner.start(doc.id)); runner.stop(); f.h.sched.advance(0.4)
	check("Stop clears active run", not runner.busy() and runner.runs[#runner.runs].status == "aborted")
	f.healthy(); f.close()
end)

case("workspace files and folders can be deleted with their bindings", function()
	local f = F.new(); local files = f.env.require("runtime/code_files")
	local store = f.env.require("runtime/code_store"); store.init()
	assert(files.create("scratch.lua", false))
	check("a new file is recognised", files.isDir("scratch.lua") == false)
	local opened = assert(files.open("scratch.lua"))
	check("opening a file binds it", files.binding(opened.documentId) ~= nil and files.dirty(opened.documentId) == false)
	local removed, why = files.delete("scratch.lua")
	check("the file is deleted", removed ~= nil and removed.isDir == false, why)
	check("its binding is dropped", files.binding(opened.documentId) == nil)
	check("and it no longer lists", #(files.children("") or {}) == 0)
	assert(files.create("nested", true))
	check("a folder is recognised before deletion", files.isDir("nested") == true)
	local folder, folderWhy = files.delete("nested")
	check("the folder is deleted", folder ~= nil and folder.isDir == true, folderWhy)
	check("the workspace root is never deletable", files.delete("") == nil)
	f.healthy(); f.close()
end)

case("the luacid fallback degrades cleanly when the host cannot run it", function()
	local f = F.new(); local caps = f.env.require("runtime/caps"); local luacid = f.env.require("runtime/luacid")
	local saved = { loadstring = caps.fn.loadstring, bytecode = caps.fn.getscriptbytecode, request = caps.fn.request }
	caps.fn.loadstring = nil
	check("without a compiler the fallback reports unavailable", not luacid.available())
	check("and install explains what is missing",
		tostring(select(2, luacid.install())):find("compile", 1, true) ~= nil)
	caps.fn.loadstring = saved.loadstring
	caps.fn.getscriptbytecode = nil
	check("bytecode access is required", not luacid.available())
	caps.fn.request = nil
	check("an HTTP request function is required", not luacid.available())
	caps.fn.getscriptbytecode, caps.fn.request = saved.bytecode, saved.request
	check("the embedded source is intact", type(luacid.SOURCE) == "string" and #luacid.SOURCE > 1000
		and luacid.SOURCE:find("getgenv().decompile", 1, true) ~= nil)
	f.healthy(); f.close()
end)

case("Code tools share the live store and bounded scoped detail reads", function()
	local f = F.new(); f.tools({ "coding", "instance", "remotes", "script" })
	local store = f.env.require("runtime/code_store"); store.init(); local doc = store.active()
	local first = f.dispatch("code_write", { document_id = doc.id, code = "return 11" })
	check("empty doc accepts first write", first.ok and doc.source == "return 11")
	check("read returns revision", f.dispatch("code_read", { document_id = doc.id }).data.revision == doc.revision)
	check("tool refuses stale revision", not f.dispatch("code_write", { document_id = doc.id, code = "return 22", expected_revision = 0 }).ok)
	local result = f.dispatch("code_run", { document_id = doc.id, expected_revision = doc.revision })
	check("code_run uses managed runner", result.ok and has(result.text, "11") and result.data.runId)
	local N = f.env.require("tools/native_helpers").forGroup("instance")
	local summary = N.result({ value = string.rep("long value ", 1000), truth = false }, "Large result")
	check("large result keeps a bounded reader reference", summary.data.readTool == "instance_result_read" and #f.h.json.encode(summary) < 6000)
	check("reader cannot cross disabled group boundary", not f.dispatch("workspace_result_read", { result_id = summary.data.resultId }).ok)
	local detail = f.dispatch("instance_result_read", { result_id = summary.data.resultId, path = { "truth" } })
	check("false survives retained lookup", detail.ok and detail.data.value == false)
	f.healthy(); f.close()
end)

case("large immutable file sources reuse references and never overwrite drafts", function()
	local f = F.new(); local fs = f.env.require("runtime/fsx"); local sources = f.env.require("runtime/script_sources")
	local content = string.rep("-- source\n", 29000); assert(fs.write("large.lua", content, { scope = "pastes" }))
	local before = 0; for _ in pairs(f.h.files) do before = before + 1 end
	local item = assert(sources.fromFile("pastes/large.lua"))
	local after = 0; for _ in pairs(f.h.files) do after = after + 1 end
	check("large file is reused", before == after and item.path == "pastes/large.lua")
	local page = assert(sources.read(item.id, 1, 6000)); check("source page bounded and exact", #page.text == 6000 and page.nextOffset == 6001)
	local bridge = f.env.require("tools/source_documents"); local opened = assert(bridge.open({ sourceId = item.id }))
	check("large source opens read-only by reference", opened.readOnly and opened.sourceId == item.id)
	local small = assert(sources.keep("return 1", "synthetic", "Small.lua")); local doc = assert(bridge.open({ sourceId = small.id }))
	local store = f.env.require("runtime/code_store"); assert(store.update(doc.documentId, "return 'user draft'"))
	local reopened = assert(bridge.open({ sourceId = small.id }))
	check("reopening source preserves edited draft", reopened.documentId ~= doc.documentId and store.resolve(doc.documentId).source == "return 'user draft'")
	f.close()
end)

case("all native Code destinations build and preserve text through navigation", function()
	local h = require("env").new(); h.setViewport(1280, 800)
	local app = assert(h.boot()); h.settle(0.5); app.app.show("code"); h.settle(0.3)
	local panel = assert(app.app.panels and app.app.panels.code or app.app.codePanel or app.app.currentPanel, "Code panel handle")
	-- Find the public native panel handle without reaching through GUI text.
	if not panel.navigate then panel = app.app.views and app.app.views.code or panel end
	local box = assert(h.byName("SourceInput", app.app.screen), "native source input")
	box.Text = "-- kept draft\nreturn 5"; h.settle(0.1)
	check("native editor is multiline and raw", box.MultiLine and not box.RichText and not box.TextWrapped)
	local env = app.env; local store = env and env.require("runtime/code_store")
	check("bundle exposes shared store", store and store.active().source == box.Text)
	for _, destination in ipairs({ "Explorer", "Remotes", "Output", "History", "Library", "Game changes", "Editor" }) do
		panel.navigate(destination); h.settle(0.2)
		check(destination .. " has native view", panel.views[destination] ~= nil)
	end
	check("navigation preserved source", store.active().source == "-- kept draft\nreturn 5")
	check("native fixtures have no async errors", #h.errors() == 0)
	check("native fixtures have valid property types", #h.instanceState.typeErrors == 0)
	app.unload()
end)

suite.finish()
