'use strict';

// Embeds assets/luacid decompiler.lua as src/runtime/luacid.lua.
//
//   node tools/build_luacid.js
//   node tools/build_luacid.js --check
//
// The asset is the source of truth. The generated module wraps it in a factory
// that installs it on demand and hands back the decompiler it publishes, so the
// client can fall back to luacid when a host has no native decompiler or its
// decompiler fails. Do not edit the generated file directly.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const assetPath = path.join(root, 'assets', 'luacid decompiler.lua');
const outPath = path.join(root, 'src', 'runtime', 'luacid.lua');
const check = process.argv.includes('--check');

const asset = fs.readFileSync(assetPath, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
if (asset.includes(']==]')) throw new Error('the asset contains the long-string delimiter ]==]');

const output = `-- The luacid decompiler, embedded so a host whose own decompiler is missing or
-- failed still has a path to a script's source.
--
-- Generated by tools/build_luacid.js from assets/luacid decompiler.lua. Do not
-- edit directly: change the asset and rebuild.
--
-- The embedded source runs under the host's own executor functions (loadstring,
-- getscriptbytecode and an HTTP request function) and returns source text from
-- the luacid service. The wrapper installs it once and hands back the decompiler
-- it publishes; the module is only touched when a script has to be decompiled and
-- the host's own tool failed.
return function(env)
\tlocal caps = env.require("runtime/caps")

\tlocal M = { installed = nil }

\tM.SOURCE = [==[
${asset}
]==]

\tfunction M.available()
\t\treturn caps.fn.loadstring ~= nil and caps.fn.getscriptbytecode ~= nil and caps.fn.request ~= nil
\tend

\t-- Compiles and runs the fallback once, then hands back the function it
\t-- publishes. A failed install is retried, because the reason may have been
\t-- transient. Any native decompiler global is restored afterwards so the
\t-- fallback cannot silently replace the host's own tool.
\tfunction M.install()
\t\tif M.installed then return M.installed end
\t\tif caps.fn.loadstring == nil then return nil, "the host cannot compile code (loadstring is unavailable)" end
\t\tif caps.fn.getscriptbytecode == nil then return nil, "the host cannot read script bytecode (getscriptbytecode is unavailable)" end
\t\tif caps.fn.request == nil then return nil, "the host has no executor HTTP function for luacid" end
\t\tlocal getgenv = caps.fn.getgenv
\t\tlocal previous
\t\tif getgenv then
\t\t\tlocal okEnv, globals = pcall(getgenv)
\t\t\tif okEnv and type(globals) == "table" then
\t\t\t\tprevious = globals.decompile
\t\t\t\tif globals.request == nil then globals.request = caps.fn.request end
\t\t\tend
\t\tend
\t\tlocal loader, why = caps.fn.loadstring(M.SOURCE)
\t\tif not loader then return nil, "luacid could not be compiled: " .. tostring(why) end
\t\tlocal ok, err = pcall(loader)
\t\tif not ok then return nil, "luacid failed to initialise: " .. tostring(err) end
\t\tlocal decompiler = getgenv and getgenv().decompile or nil
\t\tif getgenv and type(decompiler) == "function" then
\t\t\tpcall(function() getgenv().decompile = previous end)
\t\tend
\t\tif type(decompiler) ~= "function" then return nil, "luacid did not publish a decompiler" end
\t\tM.installed = decompiler
\t\treturn decompiler
\tend

\treturn M
end
`;

const normalize = text => text.replace(/\r\n/g, '\n');
if (check) {
  const current = fs.existsSync(outPath) ? normalize(fs.readFileSync(outPath, 'utf8')) : null;
  if (current !== normalize(output)) {
    process.stderr.write('src/runtime/luacid.lua is stale; run node tools/build_luacid.js\n');
    process.exitCode = 1;
  } else {
    process.stdout.write('src/runtime/luacid.lua is current\n');
  }
} else {
  fs.writeFileSync(outPath, output, 'utf8');
  process.stdout.write('wrote src/runtime/luacid.lua, ' + output.length + ' bytes\n');
}
