'use strict';

// Deterministic, dependency-free distribution. The client embeds only the
// reference guide; generated scripts fetch the separate library from GitHub.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const check = process.argv.includes('--check');
for (const option of process.argv.slice(2)) {
  if (option !== '--check') throw new Error('Unknown option: ' + option);
}
const read = file => fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
const metadata = JSON.parse(read('ui-lib/library.json'));
const sha256 = source => crypto.createHash('sha256').update(source).digest('hex');
const luaString = value => JSON.stringify(value).replace(/\\u([0-9a-f]{4})/gi, (_, digits) => String.fromCharCode(parseInt(digits, 16)));
const luaLong = source => {
  let equals = '=';
  while (source.includes(']' + equals + ']')) equals += '=';
  return '[' + equals + '[\n' + source + ']' + equals + ']';
};
const files = fs.readdirSync(path.join(root, 'ui-lib/src')).filter(file => file.endsWith('.lua')).sort();
const modules = files.map(file => {
  const source = read('ui-lib/src/' + file).trimEnd();
  if (!/^return function\(env\)/.test(source.replace(/^(?:--[^\n]*\n|\s)+/, ''))) {
    throw new Error(file + ' must return an env factory');
  }
  return { id: file.slice(0, -4), source, bytes: Buffer.byteLength(source), sha256: sha256(source) };
});
const ids = new Set(modules.map(module => module.id));
for (const module of modules) {
  for (const match of module.source.matchAll(/env\.require\("([^"]+)"\)/g)) {
    if (!ids.has(match[1])) throw new Error(module.id + ': missing dependency ' + match[1]);
  }
}
const loader = read('ui-lib/loader.lua').trimEnd();
const bundle = [
  '-- Project UAI UI LIB v' + metadata.version,
  '-- Generated by node tools/build_ui_lib.js. Edit ui-lib/src, never this file.',
  '-- ' + metadata.repository,
  '-- local UI = loadstring(game:HttpGet(' + luaString(metadata.url) + '))()',
  'local __UI_METADATA = { ' + Object.entries(metadata).map(([key, value]) => '[' + luaString(key) + '] = ' + luaString(value)).join(', ') + ' }',
  'local __UI_MODULES = {}',
  ...modules.map(module => '\n-- ' + module.id + '\n__UI_MODULES[' + luaString(module.id) + '] = (function()\n' + module.source + '\nend)()'),
  '\n' + loader,
  '',
].join('\n');
const manifest = {
  format: 'project-uai-ui', version: metadata.version, sha256: sha256(bundle),
  bytes: Buffer.byteLength(bundle), loaderSha256: sha256(loader),
  modules: modules.map(({ id, bytes, sha256 }) => ({ id, bytes, sha256 })),
};
const guide = read('docs/UI_LIBRARY.md');
const sections = {};
const headings = [...guide.matchAll(/^## ([^\n]+)\n/gm)];
for (let index = 0; index < headings.length; index++) {
  const match = headings[index];
  const key = match[1].trim().toLowerCase().replace(/[^a-z0-9]+/g, '_');
  sections[key] = guide.slice(match.index, headings[index + 1]?.index ?? guide.length).trimEnd() + '\n';
}
if (!sections.quickstart || !sections.controls || !sections.lifecycle) throw new Error('UI guide requires Quickstart, Controls, and Lifecycle sections');
const reference = [
  '-- Generated from docs/UI_LIBRARY.md by tools/build_ui_lib.js; edit the Markdown.',
  'return function(env)',
  '\treturn {',
  '\t\tversion = ' + luaString(metadata.version) + ',',
  '\t\turl = ' + luaString(metadata.url) + ',',
  '\t\trepository = ' + luaString(metadata.repository) + ',',
  '\t\tsections = {',
  ...Object.entries(sections).map(([key, body]) => '\t\t\t[' + luaString(key) + '] = ' + luaLong(body) + ','),
  '\t\t},',
  '\t}',
  'end',
  '',
].join('\n');
const artifacts = {
  'dist/uai-ui.lua': bundle,
  'dist/uai-ui.manifest.json': JSON.stringify(manifest, null, 2) + '\n',
  'src/runtime/ui_library_docs.lua': reference,
};
for (const [file, source] of Object.entries(artifacts)) {
  if (check) {
    if (!fs.existsSync(path.join(root, file)) || read(file) !== source) throw new Error(file + ' is stale; run node tools/build_ui_lib.js');
  } else {
    fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    fs.writeFileSync(path.join(root, file), source);
  }
}
console.log('UI LIB v' + metadata.version + ': ' + modules.length + ' modules, ' + Buffer.byteLength(bundle) + ' bytes; ' + (check ? 'artifacts current' : 'bundle and agent reference built'));
