-- Pack PNG icons from assets/icons/*.png into src/ui/assets.lua as base64 strings.
--
-- Usage:
--   luajit tools/pack_icons.lua

local WINDOWS = package.config:sub(1, 1) == "\\"

local b = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

local function b64encode(data)
	local out = {}
	local len = #data
	for i = 1, len, 3 do
		local a = data:byte(i)
		local b_byte = data:byte(i + 1)
		local c = data:byte(i + 2)
		local n = a * 65536 + (b_byte or 0) * 256 + (c or 0)
		local c1 = math.floor(n / 262144) % 64 + 1
		local c2 = math.floor(n / 4096) % 64 + 1
		local c3 = math.floor(n / 64) % 64 + 1
		local c4 = n % 64 + 1
		out[#out + 1] = b:sub(c1, c1) .. b:sub(c2, c2)
		if b_byte then
			out[#out + 1] = b:sub(c3, c3)
		else
			out[#out + 1] = "="
		end
		if c then
			out[#out + 1] = b:sub(c4, c4)
		else
			out[#out + 1] = "="
		end
	end
	return table.concat(out)
end

local cmd = WINDOWS
	and 'dir /b "assets\\icons\\*.png" 2>nul'
	or 'ls -1 assets/icons/*.png 2>/dev/null'

local pipe = io.popen(cmd)
if not pipe then
	io.stderr:write("cannot list assets/icons\n")
	os.exit(1)
end

local files = {}
for line in pipe:lines() do
	local clean = line:gsub("^assets[\\/]+icons[\\/]+", ""):gsub("%s+$", "")
	if clean:match("%.png$") then
		files[#files + 1] = clean
	end
end
pipe:close()
table.sort(files)

if #files == 0 then
	io.stderr:write("no PNG files found in assets/icons/\n")
	os.exit(1)
end

local lines = {
	"-- Embedded custom icon assets packed from assets/icons/*.png.",
	"--",
	"-- Generated by tools/pack_icons.lua. Do not edit directly.",
	"return function(env)",
	"\tlocal M = { VERSION = 2 }",
	"",
	"\tlocal B = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\"",
	"\tlocal T = {}",
	"\tfor i = 1, #B do T[B:byte(i)] = i - 1 end",
	"",
	"\tfunction M.decode(data)",
	"\t\tdata = data:gsub(\"[^%w%+%/%=]\", \"\")",
	"\t\tlocal out = {}",
	"\t\tlocal len = #data",
	"\t\tfor i = 1, len, 4 do",
	"\t\t\tlocal c1 = T[data:byte(i)] or 0",
	"\t\t\tlocal c2 = T[data:byte(i + 1)] or 0",
	"\t\t\tlocal b3 = data:byte(i + 2)",
	"\t\t\tlocal b4 = data:byte(i + 3)",
	"\t\t\tlocal c3 = (b3 and b3 ~= 61) and T[b3] or 0",
	"\t\t\tlocal c4 = (b4 and b4 ~= 61) and T[b4] or 0",
	"\t\t\tlocal n = c1 * 262144 + c2 * 4096 + c3 * 64 + c4",
	"\t\t\tout[#out + 1] = string.char(math.floor(n / 65536) % 256)",
	"\t\t\tif b3 and b3 ~= 61 then",
	"\t\t\t\tout[#out + 1] = string.char(math.floor(n / 256) % 256)",
	"\t\t\tend",
	"\t\t\tif b4 and b4 ~= 61 then",
	"\t\t\t\tout[#out + 1] = string.char(n % 256)",
	"\t\t\tend",
	"\t\tend",
	"\t\treturn table.concat(out)",
	"\tend",
	"",
	"\tM.icons = {",
}

local totalRaw = 0
for _, file in ipairs(files) do
	local path = "assets/icons/" .. file
	local h = io.open(path, "rb")
	if not h then
		io.stderr:write("cannot read " .. path .. "\n")
		os.exit(1)
	end
	local raw = h:read("*a")
	h:close()
	totalRaw = totalRaw + #raw
	local name = file:gsub("%.png$", "")
	local encoded = b64encode(raw)
	lines[#lines + 1] = string.format("\t\t[%q] = %q,", name, encoded)
end

lines[#lines + 1] = "\t}"
lines[#lines + 1] = ""
lines[#lines + 1] = "\treturn M"
lines[#lines + 1] = "end"
lines[#lines + 1] = ""

local out = table.concat(lines, "\n")
local outPath = "src/ui/assets.lua"
for _, option in ipairs(arg or {}) do
	if option == "--check" then
		local current = io.open(outPath, "rb")
		local body = current and current:read("*a")
		if current then current:close() end
		if not body or body:gsub("\r\n", "\n") ~= out then
			io.stderr:write("Embedded icons are stale; run luajit tools/pack_icons.lua\n"); os.exit(1)
		end
		print("Embedded icons are current")
		return
	end
end
local dest = io.open(outPath, "wb")
if not dest then
	io.stderr:write("cannot open " .. outPath .. " for writing\n")
	os.exit(1)
end
dest:write(out)
dest:close()

print(string.format("Packed %d icons (%d bytes raw, %d bytes module) into %s", #files, totalRaw, #out, outPath))
