// tools/sync_pricing.js
// Fetches model pricing from OpenRouter & LiteLLM, normalizes model IDs for all providers,
// and generates src/agent/pricing.lua.

const fs = require('fs');
const path = require('path');

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

async function fetchJson(url) {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': 'ProjectUAI-Sync/1.0' } });
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
    return await res.json();
  } catch (err) {
    console.warn(`Failed to fetch ${url}:`, err.message);
    return null;
  }
}

function roundPrice(num) {
  if (num == null || isNaN(num)) return 0;
  return Math.round(num * 1000000) / 1000000;
}

async function main() {
  console.log('Fetching OpenRouter models...');
  const openRouterData = await fetchJson('https://openrouter.ai/api/v1/models');

  console.log('Fetching LiteLLM models database...');
  const liteLlmData = await fetchJson('https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json');

  const prices = new Map();

  function recordPrice(key, prompt1M, completion1M) {
    if (!key || typeof key !== 'string') return;
    const k = key.trim().toLowerCase();
    if (!k || k.length < 2) return;
    if (prices.has(k)) return; // First source has priority
    prices.set(k, [roundPrice(prompt1M), roundPrice(completion1M)]);
  }

  function addVariants(rawKey, prompt1M, completion1M) {
    recordPrice(rawKey, prompt1M, completion1M);

    // Strip :free, :beta, :nitro, :online, :extended
    const untagged = rawKey.replace(/:[a-z0-9_-]+$/i, '');
    if (untagged !== rawKey) recordPrice(untagged, prompt1M, completion1M);

    // Strip namespace e.g. "openai/gpt-4o" -> "gpt-4o"
    const parts = untagged.split('/');
    if (parts.length > 1) {
      const bare = parts.slice(1).join('/');
      recordPrice(bare, prompt1M, completion1M);

      // Dash/dot replacements: "claude-3.5-sonnet" <-> "claude-3-5-sonnet"
      if (bare.includes('.')) {
        recordPrice(bare.replace(/\./g, '-'), prompt1M, completion1M);
      }
    }

    if (untagged.includes('.')) {
      recordPrice(untagged.replace(/\./g, '-'), prompt1M, completion1M);
    }
  }

  // 1. LiteLLM models (official upstream direct provider prices)
  if (liteLlmData && typeof liteLlmData === 'object') {
    for (const [rawKey, info] of Object.entries(liteLlmData)) {
      if (!info || typeof info !== 'object') continue;
      const inToken = info.input_cost_per_token;
      const outToken = info.output_cost_per_token;
      if (typeof inToken === 'number' && typeof outToken === 'number') {
        addVariants(rawKey, inToken * 1e6, outToken * 1e6);
      }
    }
  }

  // 2. OpenRouter models (broad multi-provider coverage)
  if (openRouterData && Array.isArray(openRouterData.data)) {
    for (const model of openRouterData.data) {
      const p = model.pricing;
      if (!p) continue;
      const prompt1M = parseFloat(p.prompt || 0) * 1e6;
      const completion1M = parseFloat(p.completion || 0) * 1e6;
      addVariants(model.id, prompt1M, completion1M);
    }
  }

  // 3. Essential manual baselines & Free models
  const baselines = {
    'big-pickle': [0, 0],
    'minipickle': [0, 0],
    'gpt-4o': [2.50, 10.00],
    'gpt-4o-mini': [0.15, 0.60],
    'gpt-4.1': [2.00, 8.00],
    'gpt-4.1-mini': [0.40, 1.60],
    'o1': [15.00, 60.00],
    'o1-mini': [1.10, 4.40],
    'o3-mini': [1.10, 4.40],
    'claude-haiku': [1.00, 5.00],
    'claude-sonnet': [3.00, 15.00],
    'claude-sonnet-5': [2.00, 10.00],
    'claude-opus': [15.00, 75.00],
    'claude-opus-4-6': [5.00, 25.00],
    'claude-opus-4-7': [5.00, 25.00],
    'claude-opus-4-8': [5.00, 25.00],
    'claude-opus-5': [5.00, 25.00],
    'claude-fable-5': [10.00, 50.00],
    'claude-mythos-5': [10.00, 50.00],
    'deepseek-chat': [0.27, 1.10],
    'deepseek-reasoner': [0.55, 2.19],
    'gemini-2.5-flash': [0.30, 2.50],
    'gemini-3.7-flash': [0.75, 3.75],
    'gemini-3.8-flash': [0.75, 3.75],
    'llama-3.3-70b': [0.59, 0.79],
    'llama-3.1-8b': [0.05, 0.08],
    'mistral-large': [2.00, 6.00],
    'mistral-small': [0.20, 0.60],
    'grok-4': [3.00, 15.00],
    'grok-3-mini': [0.30, 0.50],
    'qwen': [0.40, 0.80],
  };

  for (const [k, v] of Object.entries(baselines)) {
    addVariants(k, v[0], v[1]);
  }

  console.log(`Compiled ${prices.size} unique model pricing entries.`);

  // Sort keys for deterministic output
  const sortedKeys = Array.from(prices.keys()).sort();

  const lines = [
    '-- Model pricing directory for in/out tokens per 1,000,000 tokens.',
    '-- Format: { promptCostPer1M, completionCostPer1M }',
    '-- Generated by tools/sync_pricing.js from OpenRouter & LiteLLM datasets.',
    'return function(env)',
    '\tlocal M = {}',
    '',
    '\tlocal PRICES = {',
  ];

  for (const k of sortedKeys) {
    const [prompt, completion] = prices.get(k);
    // Sanitize key string for Lua
    const safeKey = k.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    lines.push(`\t\t["${safeKey}"] = { ${prompt}, ${completion} },`);
  }

  lines.push('\t}');
  lines.push('');
  lines.push('\tfunction M.priceFor(model, record)');
  lines.push('\t\tlocal id = tostring(model or ""):lower():gsub("^%s+", ""):gsub("%s+$", "")');
  lines.push('\t\tif id == "" then return nil end');
  lines.push('');
  lines.push('\t\t-- 1. Free/local providers always cost $0.00');
  lines.push('\t\tif record then');
  lines.push('\t\t\tif record.preset == "ollama" or record.preset == "lmstudio" then');
  lines.push('\t\t\t\treturn { 0, 0 }');
  lines.push('\t\t\tend');
  lines.push('\t\t\tlocal base = tostring(record.baseUrl or ""):lower()');
  lines.push('\t\t\tif base:find("localhost", 1, true) or base:find("127.0.0.1", 1, true) then');
  lines.push('\t\t\t\treturn { 0, 0 }');
  lines.push('\t\t\tend');
  lines.push('\t\t\tlocal registry = env.require("provider/registry")');
  lines.push('\t\t\tif registry and registry.isOpencode and registry.isOpencode(record) then');
  lines.push('\t\t\t\tif id == "big-pickle" or id == "minipickle" or id:find(":free", 1, true) then');
  lines.push('\t\t\t\t\treturn { 0, 0 }');
  lines.push('\t\t\t\tend');
  lines.push('\t\t\tend');
  lines.push('\t\tend');
  lines.push('');
  lines.push('\t\t-- 2. Exact match on raw ID');
  lines.push('\t\tif PRICES[id] then return PRICES[id] end');
  lines.push('');
  lines.push('\t\t-- 3. Normalized match without provider prefix (e.g. openai/gpt-4o -> gpt-4o)');
  lines.push('\t\tlocal bare = id:gsub("^[^/]+/", "")');
  lines.push('\t\tif PRICES[bare] then return PRICES[bare] end');
  lines.push('');
  lines.push('\t\t-- 4. Dot-to-dash variations (e.g. claude-3.5-sonnet -> claude-3-5-sonnet)');
  lines.push('\t\tlocal dashed = id:gsub("%.", "-")');
  lines.push('\t\tif PRICES[dashed] then return PRICES[dashed] end');
  lines.push('\t\tlocal bareDashed = bare:gsub("%.", "-")');
  lines.push('\t\tif PRICES[bareDashed] then return PRICES[bareDashed] end');
  lines.push('');
  lines.push('\t\t-- 5. Longest prefix matching for dated snapshots (e.g. gpt-4o-2024-11-20 -> gpt-4o)');
  lines.push('\t\tlocal best, bestLen = nil, 0');
  lines.push('\t\tfor prefix, price in pairs(PRICES) do');
  lines.push('\t\t\tif #prefix >= 4 and id:find(prefix, 1, true) and #prefix > bestLen then');
  lines.push('\t\t\t\tbest, bestLen = price, #prefix');
  lines.push('\t\t\tend');
  lines.push('\t\tend');
  lines.push('\t\tif best then return best end');
  lines.push('');
  lines.push('\t\tfor prefix, price in pairs(PRICES) do');
  lines.push('\t\t\tif #prefix >= 4 and bare:find(prefix, 1, true) and #prefix > bestLen then');
  lines.push('\t\t\t\tbest, bestLen = price, #prefix');
  lines.push('\t\t\tend');
  lines.push('\t\tend');
  lines.push('\t\treturn best');
  lines.push('\tend');
  lines.push('');
  lines.push('\tM.PRICES = PRICES');
  lines.push('\treturn M');
  lines.push('end\n');

  const outPath = path.join(__dirname, '..', 'src', 'agent', 'pricing.lua');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log(`Saved ${outPath} successfully.`);
}

main().catch(err => {
  console.error('Sync failed:', err);
  process.exit(1);
});
